### ISSUE TITLE
This looks really good

### ISSUE THREAD

**Issue by MostHated** [vncastanheira/Waypoints#1]
Hey there,
    I wanted to say that this looks like a really decent project. I was wondering if there were any plans on adding any sort of spawning manager to the waypoint setup or if it will just be managed individually with a script on each prefab that is to spawn? I have been looking for something easy to use but powerful enough to use for different types of pedestrians (also different speeds of movement) as well as vehicle traffic throughout a small city, so it would be great to be able to drag over a few different npc prefabs (and vehicles on their own separate waypoint setup) and set them up a route they can take through the city which can randomly spawn ones of different types and speeds. Perhaps for vehicles have different speed zones, etc. 

If there is no plan for anything like that, do you plan on adding a license to this project of any sort? 

Thanks!
-MH

**Comment by vncastanheira** [comment]
Hey. 
This system wasn't really designed for that, it is supposed to be close to Half Life's pathfinding.
I'll add a MIT license, so you can fork and do what you need. 👍
